### PR TITLE
Add toast notification

### PR DESCRIPTION
**Pull request by epwinchell**
This PR replaces the Inline alerts with Toast alerts

Jira: https://projects.engineering.redhat.com/browse/SSP-1780

image

### CODE REVIEW

**Comment by epwinchell** [comment]
@dippy-bot add_label enhancement

**Comment by epwinchell** [comment]
@hsong-rh I rebased. Could you test again? Thanks.

**Comment by hsong-rh** [comment]
@epwinchell Tested, worked properly.

**Comment by epwinchell** [comment]
@dippy-bot assign @lgalis

**Pull request merged**
