### PR TITLE
Title Adjustments

### PR DESCRIPTION
**Pull request by epwinchell**
Follow-up to: https://github.com/RedHatInsights/approval-api/pull/277 addressing case changes mentioned by @sbuenafe-rh  

Date/Time comments still need to be addressed. @bzwei Can you help with those?

Screen Shot 2020-02-14 at 11 52 18 AM

### CODE REVIEW

**Comment by lgalis** [comment]
@epwinchell - can you add a screenshot?

**Comment by bzwei** [comment]
Date/Time format will be addressed in a separate PR

**Comment by sbuenafe-rh** [comment]
@epwinchell looks good! 

FYI, I'm reviewing the action button terminology with my content strategist, there might be a couple tweaks to them (this can probably be address in a separate JIRA/PR tix).

**Pull request merged**
